# -*- coding: utf-8 -*-
"""isolation_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIjT-d8o1eSb4eMS2ytWYb_iLepZ2DvX
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import IsolationForest
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import seaborn as sns
import matplotlib.pyplot as plt


# 1. LOAD TRAINING DATA

df = pd.read_csv("/content/drive/MyDrive/Train_data.csv")

print("Dataset loaded:", df.shape)
print(df['class'].value_counts())


# 2. CLEAN TARGET COLUMN

df['class'] = df['class'].astype(str).str.strip().str.lower()

# Normal = 0, Anomaly = 1
df['label'] = df['class'].apply(lambda x: 0 if x == "normal" else 1)


# 3. ENCODE CATEGORICAL COLUMNS

cat_cols = df.select_dtypes(include=['object']).columns.tolist()
cat_cols.remove('class')   # remove label column

le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col].astype(str))

print("Categorical columns encoded:", cat_cols)


# 4. TRAIN ONLY ON NORMAL DATA

normal_df = df[df['label'] == 0]

X_train = normal_df.drop(columns=['class', 'label'])
X_all = df.drop(columns=['class', 'label'])
y_all = df['label']

print("Normal training samples:", X_train.shape)


# 5. TRAIN ISOLATION FOREST

iso_model = IsolationForest(
    n_estimators=200,
    contamination='auto',       #model guesses anomaly percentage
    random_state=42
)

iso_model.fit(X_train)
print("Isolation Forest trained successfully!")


# 6. PREDICT ON FULL DATASET

y_pred = iso_model.predict(X_all)

# Convert IF output → 1 (anomaly), 0 (normal)
y_pred = [1 if p == -1 else 0 for p in y_pred]


# 7. CONFUSION MATRIX & SCORES

cm = confusion_matrix(y_all, y_pred)
acc = accuracy_score(y_all, y_pred)
prec = precision_score(y_all, y_pred)
rec = recall_score(y_all, y_pred)
f1 = f1_score(y_all, y_pred)

print("\nEvaluation Metrics:")
print("Accuracy :", acc)
print("Precision:", prec)
print("Recall   :", rec)
print("F1 Score :", f1)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()


# 8. MANUAL INPUT EXAMPLE FOR TESTING

# Example MUST include all columns except the label column
manual_example = X_train.iloc[0].copy()   # use a real row
manual_example = manual_example.to_frame().T  # convert to row

manual_pred = iso_model.predict(manual_example)
manual_pred = 1 if manual_pred[0] == -1 else 0

print("\nPrediction for manual example:", manual_pred)
print("0 = Normal, 1 = Anomaly")